"""empty message

Revision ID: 687dc52c69c1
Revises: 4e3f52e4743d
Create Date: 2021-08-05 10:58:10.178091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687dc52c69c1'
down_revision = '4e3f52e4743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
